### ISSUE TITLE
运行不了，java 11  mvn3.8.4 

### ISSUE THREAD

**Issue by Jio0oiJ** [beastars1/cosersets-spider#3]
java 苦手，这个是什么问题？

java.lang.ClassCastException: class io.github.beastars1.cosersets.MainLauncher cannot be cast to class io.vertx.core.Verticle (io.github.beastars1.cosersets.MainLauncher and io.vertx.core.Verticle are in unnamed module of loader 'app')
	at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:154)
	at io.vertx.core.impl.VerticleManager.lambda$doDeployVerticle$5(VerticleManager.java:222)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jackpoi** [comment]
你好，我这里没有复现问题，你是通过什么方式启动的？运行 MainLauncher 的 main 方法就可以启动了
